// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(module) {
    return (function() {
      var args;
      args = [module.filename].concat([].slice.call(arguments));
      return console.log.apply(console, args);
    })();
  };

}).call(this);

//# sourceMappingURL=logger.js.map
