// Generated by CoffeeScript 1.10.0
(function() {
  var Db, User, db, run;

  User = require('user');

  Db = require('db');

  db = new Db;

  db.connect();

  run = function() {
    var petya, vasya;
    vasya = new User('Вася');
    petya = new User('Петя');
    vasya.hello(petya);
    return console.log(db.getPhrase('Run successful'));
  };

  if (module.parent) {
    exports.run = run;
  } else {
    run();
  }

}).call(this);

//# sourceMappingURL=server.js.map
