// Generated by CoffeeScript 1.10.0
(function() {
  var Db;

  Db = (function() {
    function Db() {}

    Db.prototype.connect = function() {
      return this.phrases = require('./ru');
    };

    Db.prototype.getPhrase = function(name) {
      if (!this.phrases[name]) {
        throw new Error('Нет такой фразы: ' + name);
      }
      return this.phrases[name];
    };

    return Db;

  })();

  module.exports = Db;

}).call(this);

//# sourceMappingURL=index.js.map
